### ISSUE TITLE
Update Psychostats submodule

### ISSUE THREAD

**Issue by Rosenstein** [janzagata/PsychoStats-docker#1]
Could you update submodule reference used? We had many commits since https://github.com/Drek282/PsychoStats/commit/42006811b3dc4e6a723550a23f4920617e29efaa

**Comment by janzagata** [comment]
Hi, I made the PS-docker independent on PS itself. So, no submodule bumping is needed anymore. 
If you start from scratch and run install script, PS repo will be automatically cloned if its missing. 

I had no time to test it if it works with actual version of PS, so ping me if something would be off.
